### PR TITLE
fix: file name containing 'index.' is not ignored by ignoreFile regex…

### LINKED ISSUE #222: bug: file name containing 'index.' is not ignored by ignoreFile regexes
I have a file whose name contains `index.`, for example, `hello-index.pgtyped.ts`.

This file is supposed to contain unused export, so I tried to ignore it using `--ignoreFiles=pgtyped` and I expect it to be ignored.

However, this does not work as expected.

### PR DESCRIPTION
**Pull request by wongjiahau**
Fixes #222

### CODE REVIEW

**Comment by mrseanryan** [comment]
@pzavolinsky  PR to process.

Travis is still blocking - could we just turn it off?

File: ispec/_run-and-check-exit-code-zero.sh [hunk 1]
```diff
@@ -2,6 +2,7 @@
 set +e;
 
 function run {
+    echo $1
     node ../../bin/ts-unused-exports tsconfig.json --exitWithUnusedTypesCount --excludePathsFromReport=to-ignore $1
```
Comment (mrseanryan) [inline ispec/_run-and-check-exit-code-zero.sh:6]: This will drop the hard coded args:

line 18:
```
--showLineNumber
```

line 19:
```
--silent
```


Maybe $1 $2 could work.

**Review by mrseanryan — CHANGES_REQUESTED** [review]

**Comment by pzavolinsky** [comment]
@wongjiahau I just merged one @mrseanryan that flew under my radar changing the release process to GH Actions, sorry to use you as guinea pig, but could you rebase your PR to see if we get the proper CI build working?

**Comment by mrseanryan** [comment]
hi @wongjiahau  many thanks for this fix.

Finally I managed to fix the CI build for PRs,
so we got it merged :)

Sean
